# Generated by Django 3.2.7 on 2022-02-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.CharField(default=' ', max_length=140),
            preserve_default=False,
        ),
    ]
